---
- name: Add user for node_exporter
  user:
    name: "{{ node_exporter_user }}"
    shell: /bin/false

- name: Wget node_exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: /root/
    mode: '644'

- name: Unpacking
  unarchive:
    src: /root/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: /root/
    remote_src: yes
    mode: '644'

- name: Copy binary
  copy:
    src: /root/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter
    dest: "{{ node_exporter_bin_directory }}/node_exporter"
    mode: '0755'
    remote_src: yes

- name: Create systemd service
  template:
    src: templates/node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: '644'
  notify:
    - Restart node_exporter service
